### ISSUE TITLE
Hub unification: Initial launch checklist

### ISSUE THREAD

**Issue by NickSto** [galaxyproject/galaxy-hub#1480]
The initial launch of the unified Hub will consist of:
- Making the NavBar subsite dropdown visible
- No more posting new news/events on .eu

## Todo list

What do we need to finish before we do that?

- [ ] Implement dynamic middle panes: #1380
- [ ] Implement bare news/events pages: #1479
- [ ] Finish subsite homepages
