### ISSUE TITLE
Support Working Group Roadmap: 2021-2022

### ISSUE THREAD

**Issue by jennaj** [galaxyproject/galaxy-hub#727]
# Support Working Group Roadmap: 2021-2022

@jennaj @gallardoalba @tnabtaf 

Project Board https://github.com/orgs/galaxyproject/projects/19
Meeting Notes https://docs.google.com/document/d/1sfepVlmL83Nql8cfGpXKto2FmEtsYvHCkHeyX_FUWCA/edit?usp=sharing

----

## FAQ to Hub2

https://github.com/orgs/galaxyproject/projects/19#column-12535143
https://github.com/orgs/galaxyproject/projects/19#column-12947726

### Migrate most of "Support > FAQ" to other places
- [ ] Content mapping from Hub to Hub2/GTN/GHelp 
* https://github.com/orgs/galaxyproject/projects/19#card-54965537
* https://github.com/orgs/galaxyproject/projects/19#card-54963517

### Add redirects old to new content locations, even those that remain in Hub2
- [ ] /support and /learn URLs https://github.com/orgs/galaxyproject/projects/19#card-59398336

### Areas to consolidate from Hub and add to Hub2
- [ ] End-User Resources https://github.com/orgs/galaxyproject/projects/19#card-58027044

### Areas to migrate out of Hub 

1. most of /support and /learn
2. to GTN (functions) + GHelp (practical/formatting in context)
3. Content Areas (not ranked/complete -- yet) https://github.com/orgs/galaxyproject/projects/19#column-12947661

Priority Content

- [ ] Troubleshooting https://github.com/orgs/galaxyproject/projects/19#card-59398598
- [ ] Datatypes https://github.com/orgs/galaxyproject/projects/19#card-55529234
- [ ] Share or Publish + User > Preferences global share settings https://github.com/orgs/galaxyproject/projects/19#card-59378808

## FAQ to GTN

https://github.com/orgs/galaxyproject/projects/19#column-12535148

Configuration
- [ ] Searches https://github.com/orgs/galaxyproject/projects/19#card-59400006

Content
- [ ]  Improve/add _function_ coverage: https://github.com/orgs/galaxyproject/projects/19#card-59399989

## FAQ to Galaxy Help (Docs+)

https://github.com/orgs/galaxyproject/projects/19#column-12535154

### 22.XX - HOLD

Configuration:
- [ ] Admin https://github.com/orgs/galaxyproject/projects/19#card-58904779
- [ ] Docs https://github.com/orgs/galaxyproject/projects/19#card-58905037
- [ ] Other plugins https://github.com/orgs/galaxyproject/projects/19#card-58028150 && https://github.com/orgs/galaxyproject/projects/19#card-54968267

Content: Getting started, narrative/example solutions, research domain resource pages, etc
- [ ] Troubleshooting simplified and converted to Docs and link back into to GTN (Tutorials, Faqs), Youtube, Auto-screenshots, External usegalaxy.* resources, Galaxy Hub search https://help.galaxyproject.org/t/troubleshooting-resources-for-errors-or-unexpected-results/42
- [ ] Top posts converted to Docs: https://help.galaxyproject.org/search?q=troubleshooting + others (WIP)

### 22.XX

- [ ] Github versioning https://github.com/orgs/galaxyproject/projects/19#card-58904974

## GCC 2021

https://github.com/orgs/galaxyproject/projects/19#column-13825522

- [ ] Training Days https://github.com/orgs/galaxyproject/projects/19#card-58027494
- [ ] Co-Fest https://github.com/orgs/galaxyproject/projects/19#card-59156824

## GSOC 2021 -- Dropped

https://github.com/orgs/galaxyproject/projects/19#column-13825531

May get bumped if no interest

- [ ] Quota help within Galaxy with linked FAQs https://github.com/orgs/galaxyproject/projects/19#card-58905271
- [ ] Datatypes help within Galaxy with linked FAQs https://github.com/orgs/galaxyproject/projects/19#card-58028943
